Repository PreOnboarding-Team-11/YaMukJa, pull requests merged in 2024-09, with the labels that each got.

#25 [TEST] 데이터 전처리 테스트코드
  src/main/java/backend/yamukja/common/config/CustomSpringBeanJobFactory.java
  src/main/java/backend/yamukja/common/config/SecurityConfig.java
  src/main/java/backend/yamukja/place/constant/Constants.java
  src/main/java/backend/yamukja/place/controller/PlaceController.java
  src/main/java/backend/yamukja/place/job/PlaceJob.java
  src/main/java/backend/yamukja/place/model/Place.java
  src/test/java/backend/yamukja/place/config/QuartzSchedulerConfigTest.java
  src/test/java/backend/yamukja/place/controller/PlaceControllerTest.java
  src/test/java/backend/yamukja/place/service/PlaceJobExecuteTest.java
Labels: TEST

#28 [REFACTOR] Place Entity 수정 및 PlaceDVO 생성
  src/main/java/backend/yamukja/place/controller/PlaceController.java
  src/main/java/backend/yamukja/place/model/Place.java
  src/main/java/backend/yamukja/place/repository/PlaceRepository.java
  src/main/java/backend/yamukja/place/service/MappingService.java
  src/main/java/backend/yamukja/place/service/PlaceService.java
  src/main/java/backend/yamukja/place/vo/PlaceDVO.java
  src/test/java/backend/yamukja/place/config/QuartzSchedulerConfigTest.java
  src/test/java/backend/yamukja/place/controller/PlaceControllerTest.java
Labels: ♻️ REFACTOR

#26 [FEAT] 시군구 목록 API
  src/main/java/backend/yamukja/common/config/DataSourceConfig.java
  src/main/java/backend/yamukja/common/config/SecurityConfig.java
  src/main/java/backend/yamukja/place/controller/SggController.java
  src/main/java/backend/yamukja/place/model/Sgg.java
  src/main/java/backend/yamukja/place/repository/SggRepository.java
  src/main/java/backend/yamukja/place/service/SggService.java
Labels: ✨ FEAT
